name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Homebrew
      id: cache-brew
      uses: actions/cache@v3
      with:
        path: /Users/runner/Library/Caches/Homebrew
        key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-brew-

    - name: Install LLVM
      run: brew install llvm

    - name: Compile
      run: make

    - name: Run Executable
      run: ./bin/main